### ISSUE TITLE
add a new x-translator.infores extension field

### ISSUE THREAD

**Issue by newgene** [NCATSTranslator/translator_extensions#13]
Per the discussion at the Architecture call and this related issue, https://github.com/NCATSTranslator/TranslatorArchitecture/issues/59#issuecomment-883620934, let's add a new `x-translator.infores` under `x-translator` field.

The field type should be string and users can reference the possible values from this list:

https://docs.google.com/spreadsheets/d/1Ak1hRqlTLr1qa-7O0s5bqeTHukj9gSLQML1-lg6xIHM/edit#gid=293462374

We will validate the value of this field as a string with `infores:` prefix.

**Comment by RichardBruskiewich** [comment]
@newgene looks like this issue is already resolved?

**Comment by newgene** [comment]
Yes, we can close this one. Thanks @RichardBruskiewich
