### ISSUE TITLE
Add validation rule for "translator" in "tags" field

### ISSUE THREAD

**Issue by newgene** [NCATSTranslator/translator_extensions#2]
Let's add a conditional rule for "tags" field if "x-translator" extension field is provided. The rule is like this:

* If "x-translator" is provided, "tags" should contain "translator" in the value.
* If "tags" contains "translator", "x-translator" extension field should be provided.

We can use the `if-then-else` keyword from JSON Schema Draft 7, and test it using [`jsonschema`](https://python-jsonschema.readthedocs.io/) Python package.

The JSON Schema rules can be added to the existing [`x-translator` extension file]( https://github.com/NCATSTranslator/translator_extensions/blob/main/x-translator/smartapi_x-translator_schema.json).

**Comment by colleenXu** [comment]
I believe the PR made just now addresses the issue as described above. The Schema draft was updated to draft-07.

**Comment by colleenXu** [comment]
Note that currently the x-translator extension schema does not require having info / tags properties (or having x-translator) fields. So an example like below will still validate:

`{
  "tags": [
    {"name": "biothings"}],
  "info": {
  }
}`

Comment below if this behavior is not desired. @newgene
